apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mljo9eht2-go 
  janus-idp.io/tekton: mljo9eht2-go
  backstage.io/kubernetes-id: mljo9eht2-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mljo9eht2-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml